Repository perfume-pick/purple-server, pull requests merged in 2024-08, with the labels that each got.

#54 [PURPLE-107] 검색 API 및 최근 검색 API
  Dockerfile
  build.gradle
  compose-dev.yaml
  compose-local.yaml
  src/main/java/com/pikachu/purple/application/perfume/port/in/PerfumeCreateUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/port/in/PerfumeGetByKeywordUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeDocumentRepository.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeCreateApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeGetByKeywordApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeServiceImpl.java
  src/main/java/com/pikachu/purple/application/user/port/in/UserDeleteAllSearchHistoryUseCase.java
  src/main/java/com/pikachu/purple/application/user/port/in/UserGetSearchHistoryUseCase.java
  src/main/java/com/pikachu/purple/application/user/port/in/UserSaveSearchHistoryUseCase.java
  src/main/java/com/pikachu/purple/application/user/port/out/UserSearchHistoryRepository.java
  src/main/java/com/pikachu/purple/application/user/service/application/UserDeleteAllSearchHistoryApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/application/UserGetSearchHistoryApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/application/UserSaveSearchHistoryApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/domain/UserSearchHistoryService.java
  src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserSearchHistoryServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/dto/response/GetPerfumeByKeywordResponse.java
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
  src/main/java/com/pikachu/purple/bootstrap/user/dto/response/SearchPageResponse.java
  src/main/java/com/pikachu/purple/domain/user/entity/UserSearchHistory.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/common/ElasticSearchConfig.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/perfume/adaptor/PerfumeElasticSearchAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/perfume/repository/PerfumeElasticSearchRepository.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/perfume/vo/PerfumeDocument.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/UserSearchHistoryRedisAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/entity/UserSearchHistoryRedisHash.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/UserSearchHistoryRedisRepository.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/impl/UserSearchHistoryRedisRepositoryImpl.java
  src/main/resources/application.yaml
Labels: ✨기능, 🌍인프라

#66 [PURPLE-122] Refresh Token API 에러 해결
  src/main/java/com/pikachu/purple/application/user/service/application/RefreshJwtTokenApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/util/SocialLoginService.java
  src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/common/exception/GlobalExceptionHandler.java
  src/main/resources/application.yaml
Labels: 🎯리팩토링, 🛠️버그

#67 [PURPLE-123] ElasticSearch 롤백, 검색 API out port 변경
  Dockerfile
  compose-dev.yaml
  compose-local.yaml
  src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeCreateApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/common/ElasticSearchConfig.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/perfume/adaptor/PerfumeElasticSearchAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/perfume/repository/PerfumeElasticSearchRepository.java
  src/main/java/com/pikachu/purple/infrastructure/elasticsearch/perfume/vo/PerfumeDocument.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeBrandJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
  src/main/resources/application.yaml
Labels: ✨기능, 🚨긴급

#70 [PURPLE-000] @Secured 어노테이션 임시 제거
  src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
  src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
Labels: 🛠️버그

#72 [PURPLE-000] token resolve 로직에서 "" 문자열 따옴표가 삽입되는 문제 해결
  src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/common/security/JwtAuthenticationFilter.java
  src/main/java/com/pikachu/purple/support/security/auth/vo/JwtClaims.java
Labels: 🚨긴급, 🛠️버그
