Repository perfume-pick/purple-server, pull requests merged in 2024-12, with the labels that each got.

#152 [PURPLE-198] 초기 적재 스크립트 수정
  .gitignore
  src/main/resources/data/.env_sample
  src/main/resources/data/init_data.ipynb
Labels: 🌍인프라, 🎯리팩토링

#154 [PURPLE-200] 향수 상세 페이지 내 별점 조회 API 수정
  src/main/java/com/pikachu/purple/application/review/common/dto/ReviewByUserDTO.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewByPerfumeIdAndUserApplicationService.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
Labels: 🎯리팩토링

#155 [PURPLE-201] 한글버전 컬럼 추가
  src/main/java/com/pikachu/purple/application/perfume/common/dto/BrandDTO.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeAccordDTO.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDTO.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDetailDTO.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeSimpleDTO.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/RecommendedPerfumeDTO.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/UserAccordDTO.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByBrandsApplicationService.java
  src/main/java/com/pikachu/purple/domain/accord/Accord.java
  src/main/java/com/pikachu/purple/domain/perfume/Brand.java
  src/main/java/com/pikachu/purple/domain/perfume/Note.java
  src/main/java/com/pikachu/purple/domain/perfume/Perfume.java
  src/main/java/com/pikachu/purple/domain/perfume/PerfumeAccord.java
  src/main/java/com/pikachu/purple/domain/user/UserAccord.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/accord/entity/AccordJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/BrandJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/NoteJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeAccordJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/user/entity/UserAccordJpaEntity.java
  src/main/resources/db/migration/V202412151029234__add_column_korean_name.sql
Labels: 🎯리팩토링

#156 [PURPLE-000] 한글 컬럼 추가
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeAccordDTO.java
Labels: 🎯리팩토링

#160 [PURPLE-204] DTO 한글 컬럼 반환
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByReviewCountApplicationService.java
  src/main/java/com/pikachu/purple/application/review/common/dto/ReviewWithPerfumeDTO.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetTopThreeReviewedBrandsApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetPolarizedUserAccordsByUserApplicationService.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
Labels: 🎯리팩토링

#161 [PURPLE-205] 최근 검색 기록 저장 API로 분리
  src/main/java/com/pikachu/purple/bootstrap/search/controller/SearchController.java
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
Labels: 🎯리팩토링

#162 [PURPLE-206] com.palantir.docker 버전 문제
  Dockerfile
Labels: 🚨긴급

#163 [PURPLE-207] com.palantir.docker 버전 문제
  Dockerfile
  build.gradle
Labels: 🚨긴급

#164 [PURPLE-208] com.palantir.docker 버전 문제
  build.gradle
Labels: 🚨긴급

#167 [PURPLE-210] 별점 집계 방식 수정 및 평점 계산 로직 추가
  src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/RecalculatePerfumeAverageScoreUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/RecalculatePerfumeAverageScoresUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/RecalculatePerfumeAverageScoreApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/RecalculatePerfumeAverageScoresApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/review/port/in/starrating/GetStarRatingsUseCase.java
  src/main/java/com/pikachu/purple/application/review/port/out/StarRatingRepository.java
  src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateOrUpdateStarRatingOnboardingApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingOnboardingApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/application/starrating/GetStarRatingsApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/application/starrating/UpdateStarRatingApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/StarRatingDomainService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/impl/StarRatingDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/statistic/port/in/starratingstatistic/GetStarRatingStatisticsUseCase.java
  src/main/java/com/pikachu/purple/application/statistic/port/in/starratingstatistic/RecountStarRatingStatisticsUseCase.java
  src/main/java/com/pikachu/purple/application/statistic/port/out/StarRatingStatisticRepository.java
  src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/GetPerfumeStatisticByPerfumeIdApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/DecreaseStarRatingStatisticApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/GetStarRatingStatisticsApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/IncreaseStarRatingStatisticApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/IncreaseStarRatingStatisticsApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/RecountStarRatingStatisticsApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/StarRatingStatisticDomainService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/admin/api/AdminApi.java
  src/main/java/com/pikachu/purple/bootstrap/admin/controller/AdminController.java
  src/main/java/com/pikachu/purple/bootstrap/batch/api/BatchApi.java
  src/main/java/com/pikachu/purple/bootstrap/batch/controller/BatchController.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/StarRatingJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/StarRatingStatisticJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/id/StarRatingStatisticId.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/StarRatingStatisticJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/vo/StarRatingStatisticCompositeKey.java
  src/main/resources/db/migration/V20241226190042__drop_star_rating_statistic_statistics_date.sql
Labels: ✨기능, 🎯리팩토링

#168 [PURPLE-211] 메인페이지, 마이페이지 어코드 한글값 추가 반환
  src/main/java/com/pikachu/purple/application/perfume/common/dto/UserAccordDTO.java
  src/main/java/com/pikachu/purple/application/user/common/dto/PolarizedUserAccordDTO.java
  src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetPolarizedUserAccordsByUserApplicationService.java
Labels: 🎯리팩토링

#169 [PURPLE-212] 메인페이지 어코드 기반 추천 향수 리스트 수정
  src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
Labels: 🎯리팩토링
