Repository perfume-pick/purple-server, pull requests merged in 2024-10, with the labels that each got.

#109 [PURPLE-164] Domain 리팩토링
  src/main/java/com/pikachu/purple/application/review/common/dto/ReviewDTO.java
  src/main/java/com/pikachu/purple/domain/accord/Accord.java
  src/main/java/com/pikachu/purple/domain/perfume/Brand.java
  src/main/java/com/pikachu/purple/domain/perfume/Note.java
  src/main/java/com/pikachu/purple/domain/perfume/Perfume.java
  src/main/java/com/pikachu/purple/domain/perfume/PerfumeAccord.java
  src/main/java/com/pikachu/purple/domain/review/Mood.java
  src/main/java/com/pikachu/purple/domain/review/Review.java
  src/main/java/com/pikachu/purple/domain/review/StarRating.java
  src/main/java/com/pikachu/purple/domain/user/User.java
  src/main/java/com/pikachu/purple/domain/user/UserAccord.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/accord/entity/AccordJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/mood/entity/MoodJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/BrandJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/NoteJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeAccordJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/id/PerfumeAccordId.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ReviewJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/StarRatingJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/user/entity/UserAccordJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/user/entity/UserJpaEntity.java
Labels: 🎯리팩토링

#111 [PURPLE-168] 통계(집계) 로직 버그 수정
  src/main/java/com/pikachu/purple/application/statistic/port/out/EvaluationStatisticRepository.java
  src/main/java/com/pikachu/purple/application/statistic/port/out/StarRatingStatisticRepository.java
  src/main/java/com/pikachu/purple/application/statistic/scheduler/EvaluationStatisticScheduler.java
  src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/GetPerfumeStatisticByPerfumeIdApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/EvaluationStatisticDomainService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/StarRatingStatisticDomainService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/EvaluationStatisticDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
  src/main/java/com/pikachu/purple/domain/perfume/FragranticaEvaluation.java
  src/main/java/com/pikachu/purple/domain/statistic/EvaluationStatistic.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/FragranticaEvaluationJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/EvaluationStatisticJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/EvaluationStatisticJpaRepository.java
Labels: 🚨긴급, 🛠️버그

#114 [PURPLE-000] 잘못된 API url 형식 수정
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
Labels: 🎯리팩토링, 🚨긴급

#115 [PURPLE-000] 평가 옵션명(=설명) 수정
  src/main/java/com/pikachu/purple/domain/evaluation/enums/EvaluationOptionType.java
Labels: 🎯리팩토링, 🚨긴급

#116 [PURPLE-000] 스케쥴 집계 오류 수정 및 스케쥴링 오류 발생 시 수동 배치 수행 API 추가
  src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
  src/main/java/com/pikachu/purple/bootstrap/batch/api/BatchApi.java
  src/main/java/com/pikachu/purple/bootstrap/batch/controller/BatchController.java
Labels: 🚨긴급, 🛠️버그

#121 [PURPLE-165] 선호/불호 노트를 위한 리팩토링
  src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/perfume/util/RecommendUserAccordsProvider.java
  src/main/java/com/pikachu/purple/application/user/port/in/useraccord/GetTopThreeUserAccordsUseCase.java
  src/main/java/com/pikachu/purple/application/user/port/out/UserAccordRepository.java
  src/main/java/com/pikachu/purple/application/user/service/application/useraccord/CreateUserAccordApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetTopThreeUserAccordsApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/domain/UserAccordDomainService.java
  src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserAccordDomainServiceImpl.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/user/adaptor/UserAccordJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/user/repository/UserAccordJpaRepository.java
Labels: 🎯리팩토링

#127 [PURPLE-181] 브랜드 평가 개수 순위 조회 API 추가
  src/main/java/com/pikachu/purple/application/review/common/dto/ReviewedBrandDTO.java
  src/main/java/com/pikachu/purple/application/review/port/in/review/GetTopThreeReviewedBrandsUseCase.java
  src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetTopThreeReviewedBrandsApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
  src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetTopThreeReviewedBrandsResponse.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewJpaRepository.java
Labels: ✨기능

#129 [PURPLE-184] 로그인 시 사용자 정보 반환
  src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java
  src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
  src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
  src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginResponse.java
Labels: 🎯리팩토링
