Repository perfume-pick/purple-server, pull requests merged in 2024-09, with the labels that each got.

#79 [PURPLE-130] 최초 로그인(회원가입) 여부 반환
  src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java
  src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
  src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
  src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginResponse.java
Labels: 🎯리팩토링

#82 [PURPLE-132] 향수어코드 order by desc 적용
  src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeAccordRepository.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeAccordDomainService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeAccordDomainServiceImpl.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeAccordJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeAccordJpaRepository.java
Labels: 🛠️버그

#81 [PURPLE-132] 프라그란티카 평가 정보 조회 API 구현
  src/main/java/com/pikachu/purple/application/evaluation/common/dto/FragranticaEvaluationDTO.java
  src/main/java/com/pikachu/purple/application/evaluation/common/dto/MostVotedOption.java
  src/main/java/com/pikachu/purple/application/evaluation/port/in/FragranticaEvaluationGetByPerfumeIdUseCase.java
  src/main/java/com/pikachu/purple/application/evaluation/port/out/FragranticaEvaluationRepository.java
  src/main/java/com/pikachu/purple/application/evaluation/service/application/FragranticaEvaluationGetByPerfumeIdApplicationService.java
  src/main/java/com/pikachu/purple/application/evaluation/service/domain/FragranticaEvaluationDomainService.java
  src/main/java/com/pikachu/purple/application/evaluation/service/domain/impl/FragranticaEvaluationDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/util/MathUtil.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/dto/response/GetFragranticaEvaluationsResponse.java
  src/main/java/com/pikachu/purple/domain/evaluation/FragranticaEvaluation.java
  src/main/java/com/pikachu/purple/domain/evaluation/enums/EvaluationField.java
  src/main/java/com/pikachu/purple/domain/evaluation/enums/EvaluationOption.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/adaptor/FragranticaEvaluationJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/entity/FragranticaEvaluationJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/repository/FragranticaEvaluationJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeBrandJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
Labels: ✨기능

#93 [PURPLE-148] 분산락 name 속성 추가
  src/main/java/com/pikachu/purple/infrastructure/redis/annotation/DistributedLock.java
  src/main/java/com/pikachu/purple/infrastructure/redis/annotation/aop/DistributedLockAop.java
Labels: 🎯리팩토링

#96 [PURPLE-152] 온보딩 별점 부여 시 집계 로직 수정
  src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingOnboardingApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/port/in/starratingstatistic/IncreaseStarRatingStatisticsUseCase.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/IncreaseStarRatingStatisticsApplicationService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
Labels: 🎯리팩토링, 🚨긴급

#105 [PURPLE-158] 최근 본 상품 생성, 조회, 삭제 API
  src/main/java/com/pikachu/purple/application/history/common/dto/SearchHistoryDTO.java
  src/main/java/com/pikachu/purple/application/history/common/dto/VisitHistoryDTO.java
  src/main/java/com/pikachu/purple/application/history/port/in/searchhistory/GetSearchHistoriesUseCase.java
  src/main/java/com/pikachu/purple/application/history/port/in/visithistory/CreateVisitHistoryUseCase.java
  src/main/java/com/pikachu/purple/application/history/port/in/visithistory/DeleteVisitHistoriesUseCase.java
  src/main/java/com/pikachu/purple/application/history/port/in/visithistory/GetVisitHistoriesUseCase.java
  src/main/java/com/pikachu/purple/application/history/port/out/VisitHistoryRepository.java
  src/main/java/com/pikachu/purple/application/history/service/application/searchhistory/GetSearchHistoriesApplicationService.java
  src/main/java/com/pikachu/purple/application/history/service/application/visithistory/CreateVisitHistoryApplicationService.java
  src/main/java/com/pikachu/purple/application/history/service/application/visithistory/DeleteVisitHistoriesApplicationService.java
  src/main/java/com/pikachu/purple/application/history/service/application/visithistory/GetVisitHistoriesApplicationService.java
  src/main/java/com/pikachu/purple/application/history/service/domain/VisitHistoryDomainService.java
  src/main/java/com/pikachu/purple/application/history/service/domain/impl/VisitHistoryDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDTO.java
  src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/GetPerfumesByIdsUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByIdsApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByKeywordApplicationService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java
  src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeDomainServiceImpl.java
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
  src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetSearchHistoriesResponse.java
  src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetVisitHistoriesResponse.java
  src/main/java/com/pikachu/purple/domain/history/VisitHistory.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/VisitHistoryRedisAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/entity/VisitHistoryRedisHash.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/VisitHistoryRedisRepository.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/impl/VisitHistoryRedisRepositoryImpl.java
Labels: ✨기능

#106 [PURPLE-153] 리뷰 평가 집계 스케쥴러 적용
  src/main/java/com/pikachu/purple/application/review/port/in/review/GetReviewsDetailWithEvaluationByUpdatedDateUseCase.java
  src/main/java/com/pikachu/purple/application/review/port/out/ReviewEvaluationRepository.java
  src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsDetailWithEvaluationByUpdatedDateApplicationService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/ReviewEvaluationDomainService.java
  src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/statistic/port/out/EvaluationStatisticRepository.java
  src/main/java/com/pikachu/purple/application/statistic/port/out/StarRatingStatisticRepository.java
  src/main/java/com/pikachu/purple/application/statistic/scheduler/EvaluationStatisticScheduler.java
  src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/EvaluationStatisticDomainService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/StarRatingStatisticDomainService.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/EvaluationStatisticDomainServiceImpl.java
  src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
  src/main/java/com/pikachu/purple/domain/review/Review.java
  src/main/java/com/pikachu/purple/domain/statistic/EvaluationStatistic.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewEvaluationJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ReviewJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewEvaluationJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewJpaRepository.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/EvaluationStatisticJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticJpaEntity.java
  src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/EvaluationStatisticJpaRepository.java
Labels: ✨기능
