Repository perfume-pick/purple-server, pull requests merged in 2025-01, with the labels that each got.

#170 [PURPLE-213] 불필요한 반환값 임시 제거
  src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
Labels: 🎯리팩토링, 💯테스트

#172 [PURPLE-215] AWS 인프라 환경 이전에 따른 CI/CD 파일 수정
  .github/workflows/dev-server-deployer.yaml
  .github/workflows/dev-server-integrator.yaml
Labels: 🌍인프라

#171 [PURPLE-214] 불필요한 호스트 변수 제거
  src/main/java/com/pikachu/purple/application/user/port/in/SocialLogoutUseCase.java
  src/main/java/com/pikachu/purple/application/user/port/in/user/DeleteUserUseCase.java
  src/main/java/com/pikachu/purple/application/user/service/application/SocialLogoutApplicationService.java
  src/main/java/com/pikachu/purple/application/user/service/application/user/DeleteUserApplicationService.java
  src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
  src/main/java/com/pikachu/purple/bootstrap/common/config/SwaggerConfig.java
  src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
  src/main/resources/application.yaml
Labels: 🎯리팩토링

#181 [PURPLE-222] 향수 평점 정보 제공에 관한 리팩토링
  src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDetailDTO.java
  src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/GetPerfumeDetailByPerfumeIdUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
  src/main/java/com/pikachu/purple/util/MathUtil.java
Labels: 🎯리팩토링

#180 [PURPLE-221] Controller 유효성 검증 추가
  src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java
  src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/RefreshJwtTokenRequest.java
  src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/SocialLoginRequest.java
  src/main/java/com/pikachu/purple/bootstrap/complaint/api/ComplaintApi.java
  src/main/java/com/pikachu/purple/bootstrap/onboarding/vo/StarRatingVO.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/api/BrandApi.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
  src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
  src/main/java/com/pikachu/purple/bootstrap/review/dto/request/CreateReviewDetailRequest.java
  src/main/java/com/pikachu/purple/bootstrap/review/dto/request/CreateReviewSimpleRequest.java
  src/main/java/com/pikachu/purple/bootstrap/search/api/SearchApi.java
  src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
Labels: 🎯리팩토링

#186 [PURPLE-225] 최근 검색기록 저장 시 중복 값 처리
  src/main/java/com/pikachu/purple/application/history/port/out/SearchHistoryRepository.java
  src/main/java/com/pikachu/purple/application/history/service/application/searchhistory/CreateSearchHistoryApplicationService.java
  src/main/java/com/pikachu/purple/application/history/service/domain/SearchHistoryDomainService.java
  src/main/java/com/pikachu/purple/application/history/service/domain/impl/SearchHistoryDomainServiceImpl.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/SearchHistoryRedisAdaptor.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/UserSearchHistoryRedisRepository.java
  src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/impl/UserSearchHistoryRedisRepositoryImpl.java
Labels: 🎯리팩토링

#189 [PERPICK-004] (statistic > evaluationstatistic) IncreaseEvaluationStatisticUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/IncreaseEvaluationStatisticService.java
Labels: 🎯리팩토링

#188 [PERPICK-005] (statistic > evaluationstatistic) RecountEvaluationStatisticsUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/RecountEvaluationStatisticsService.java
Labels: 🎯리팩토링

#187 [PERPICK-003] (statistic > evaluationstatistic) DecreaseEvaluationStatisticUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/DecreaseEvaluationStatisticService.java
Labels: 🎯리팩토링

#191 [PERPICK-008] (perfume > brand) GetBrandsUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/perfume/service/application/brand/GetBrandsService.java
Labels: 🎯리팩토링

#193 [PERPICK-011] (statistic) GetPerfumeStatisticByPerfumeIdUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/statistic/port/in/GetPerfumeStatisticUseCase.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/GetPerfumeStatisticService.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
Labels: 🎯리팩토링

#192 [PERPICK-007] (statistic > starratingstatistic) Get/RecountStarRatingStatisticsUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/GetStarRatingStatisticsService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/RecountStarRatingStatisticsService.java
Labels: 🎯리팩토링

#194 [PERPICK-009] (perfume > perfume) GetPerfumeUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/GetPerfumeUseCase.java
  src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumeService.java
Labels: 🎯리팩토링

#198 [PERPICK-014] (review > complaint) DeleteComplaintWithReviewUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/service/application/complaint/DeleteComplaintWithReviewService.java
Labels: 🎯리팩토링

#199 [PERPICK-016] (review > like) UseCase 관련 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/like/DeleteLikesUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/like/CreateLikeService.java
  src/main/java/com/pikachu/purple/application/review/service/application/like/DeleteLikeService.java
  src/main/java/com/pikachu/purple/application/review/service/application/like/DeleteLikesService.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewApplicationService.java
Labels: 🎯리팩토링

#200 [PERPICK-017] (review > mood) GetMoodsUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/mood/GetMoodsUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/mood/GetMoodsService.java
Labels: 🎯리팩토링

#201 [PERPICK-018] (review > review) CreateReview관련 UseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/review/CreateDetailedReviewUseCase.java
  src/main/java/com/pikachu/purple/application/review/port/in/review/CreateSimpleReviewUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/CreateDetailedReviewService.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/CreateSimpleReviewService.java
  src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
Labels: 🎯리팩토링

#204 [PERPICK-021] (review > review) UpdateReview관련 UseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/review/UpdateDetailedReviewUseCase.java
  src/main/java/com/pikachu/purple/application/review/port/in/review/UpdateSimpleReviewUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateDetailedReviewService.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateReviewService.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateSimpleReviewService.java
  src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
Labels: 🎯리팩토링

#208 [PERPICK-026] (review > review) GetTopThreeReviewedBrandsUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetTopThreeReviewedBrandsService.java
Labels: 🎯리팩토링

#207 [PERPICK-025] (review > review) GetReviewsDetailWithEvaluationUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/review/GetDetailedReviewsUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetDetailedReviewsService.java
  src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/RecountEvaluationStatisticsService.java
Labels: 🎯리팩토링

#205 [PERPICK-023] (review > review) GetReviewByPerfumeIdAndUserUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/review/GetCurrentUserReviewUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetCurrentUserReviewService.java
  src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
Labels: 🎯리팩토링

#206 [PERPICK-024] (review > review) GetReviewsByPerfumeIdAndSortTypeUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/review/GetReviewsUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsService.java
  src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
Labels: 🌍인프라

#202 [PERPICK-019] (review > review) Increase/DecreaseLikeCountUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/port/in/review/DecreaseReviewLikeCountUseCase.java
  src/main/java/com/pikachu/purple/application/review/port/in/review/IncreaseReviewLikeCountUseCase.java
  src/main/java/com/pikachu/purple/application/review/service/application/like/CreateLikeService.java
  src/main/java/com/pikachu/purple/application/review/service/application/like/DeleteLikeService.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/DecreaseReviewLikeCountService.java
  src/main/java/com/pikachu/purple/application/review/service/application/review/IncreaseReviewLikeCountService.java
Labels: 🎯리팩토링

#203 [PERPICK-020] (review > review) DeleteReviewUseCase 리팩토링
  src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewService.java
Labels: 🎯리팩토링
